# Generated by Django 3.2.16 on 2023-07-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_1', models.CharField(blank=True, max_length=255, verbose_name='Team 1')),
                ('t_2', models.CharField(blank=True, max_length=255, verbose_name='Team 2')),
                ('t_s_1', models.PositiveIntegerField(blank=True, verbose_name='Team 1 Score')),
                ('t_s_2', models.PositiveIntegerField(blank=True, verbose_name='Team 2 Score')),
                ('min', models.PositiveIntegerField(blank=True, verbose_name='Minutes')),
                ('sec', models.PositiveIntegerField(blank=True, verbose_name='Seconds')),
                ('quater', models.CharField(blank=True, max_length=10)),
                ('t_1_c', models.CharField(blank=True, max_length=20, verbose_name='Team 1 Color')),
                ('t_2_c', models.CharField(blank=True, max_length=20, verbose_name='Team 2 Color')),
                ('s_c', models.CharField(blank=True, max_length=20, verbose_name='Score Color')),
                ('t_c', models.CharField(blank=True, max_length=20, verbose_name='Timer Color')),
                ('q_c', models.CharField(blank=True, max_length=20, verbose_name='Quater Color')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.TimeField()),
            ],
        ),
    ]
