# Generated by Django 3.2.16 on 2023-07-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Minutes'),
        ),
        migrations.AlterField(
            model_name='match',
            name='q_c',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Quater Color'),
        ),
        migrations.AlterField(
            model_name='match',
            name='quater',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='s_c',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Score Color'),
        ),
        migrations.AlterField(
            model_name='match',
            name='sec',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Seconds'),
        ),
        migrations.AlterField(
            model_name='match',
            name='t_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Team 1'),
        ),
        migrations.AlterField(
            model_name='match',
            name='t_1_c',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Team 1 Color'),
        ),
        migrations.AlterField(
            model_name='match',
            name='t_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Team 2'),
        ),
        migrations.AlterField(
            model_name='match',
            name='t_2_c',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Team 2 Color'),
        ),
        migrations.AlterField(
            model_name='match',
            name='t_c',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Timer Color'),
        ),
        migrations.AlterField(
            model_name='match',
            name='t_s_1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Team 1 Score'),
        ),
        migrations.AlterField(
            model_name='match',
            name='t_s_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Team 2 Score'),
        ),
    ]
