# Generated by Django 3.2.16 on 2023-07-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230713_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='min',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Minutes'),
        ),
        migrations.AlterField(
            model_name='match',
            name='quater',
            field=models.CharField(blank=True, default='Q1', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='sec',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Seconds'),
        ),
    ]
