# Generated by Django 3.2.16 on 2023-07-13 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230713_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='starting_time',
        ),
        migrations.AddField(
            model_name='timer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timer',
            name='is_running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timer',
            name='pause_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timer',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timer',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
    ]
