# Generated by Django 3.2.16 on 2023-07-13 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230713_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='created',
        ),
    ]
