# Generated by Django 3.2.16 on 2023-07-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_timer_start_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timer',
        ),
    ]
